
\c animals_db_dev;

INSERT INTO animals(name, species, age, breed_origin, personality, abilities, favorite_foods, gender, borough, image_link, is_adopted) VALUES
(
'Falkor',
'Dragon',
'1500 years',
'Luckdragon',
'Optimistic, friendly, dignified, helpful and wise',
'Exahales blue fire, incredible luck, sleeps while flying',
'Does not need to eat, but likes ginger candy',
'Male',
'Brooklyn',
'http://images2.fanpop.com/images/photos/6200000/The-NeverEnding-Story-the-neverending-story-6204751-500-282.jpg',
FALSE
),
(
'Electra Golden Twinkie',
'Unicorn',
'87 years',
'Rainbow Forest',
'Outgoing, energetic, smart, friendly, intelligent, gentle',
'Telepathy, Healing Powers',
'Does not need to eat, but likes rainbow bagels and maple syrup',
'Female',
'Staten Island',
'https://i.pinimg.com/736x/80/8e/ff/808eff925ce707be590c73c76d46f392--rainbow-unicorn-the-rainbow.jpg',
FALSE
),
(
'Wicket',
'Ewok',
'163 years',
'Forest Moon of Endor',
'Intelligent, Brave, Curious, Cautious, Loyal, Musical',
'Human strength, Sensitivity to the Force, Skilled Warrior',
'Meat, forest plants, and berries',
'Male',
'Queens',
'http://www.warwickdavis.co.uk/images/webshop_wicket.jpg',
FALSE
),
(
'Buckbeak',
'Hippogriff',
'59 years',
'Italian Alps',
'Very proud, fiercely loyal and protective of those who have earned their trust, Affectionate',
'Flight, fast, strong',
'Insects, birds, and small mammals such as ferrets',
'Male',
'Bronx',
'https://images.moviepilot.com/images/c_limit,q_auto:good,w_600/dqcpyjpvthmnwhu7nplg/buckbeak-the-hippogriff.jpg',
FALSE
),
(
'Duke',
'Puppy',
'8 weeks',
'Golden Retriever',
'Affectionate, playful, energetic, friendly, Lovable',
'None',
'Bacon, Beef jerky',
'Male',
'Manhattan',
'https://i.ytimg.com/vi/2EfHtzauHcM/maxresdefault.jpg',
FALSE
),
(
'Alice',
'Dog',
'3 years',
'Long-haired Dachshund',
'Loving, cuddle-muffin, sweet, sensitive, will be attached to you!',
'None',
'Roast chicken',
'Female',
'Staten Island',
'http://www.crowndachshunds.com/wp-content/uploads/2016/11/Harps.jpg',
false
),
(
'Mrs.Norris',
'Cat',
'8 years',
'Maine Coon',
'Smart, loyal, tactful, observant',
'None, but has red eyes',
'Salmon',
'Female',
'Manhattan',
'https://upload.wikimedia.org/wikipedia/ru/f/f7/Mrs_Norris_PS.png',
FALSE
),
(
'Drogon, Rhaegal, Viserion',
'3 Baby Dragons',
'2 months',
'Essos',
'Fierce, loyal, fighters, protective, fearsome, intelligent',
'Breathe fire, flight, difficult to kill',
'Meat',
'Genderless',
'Staten Island',
'https://i.pinimg.com/originals/01/75/2f/01752fe9ebf743c9eeebdf3eedef86b1.jpg',
FALSE
),
(
'Eevee',
'Pokemon',
'3 years',
'Evolution',
'Affectionate, friendly, loving, protective',
'Adaptability, run away, can level up',
'Berries',
'Genderless',
'Brooklyn',
'https://cdn.bulbagarden.net/upload/thumb/e/e2/133Eevee.png/250px-133Eevee.png',
false
),
(
'Jiggypuff',
'Pokemon',
'5 months',
'Fairy',
'Loves to sing, very loyal, charisma',
'Mesmerizing ability, filling up with air to float, singing',
'Strawberries',
'Genderless',
'Bronx',
'https://cdn.bulbagarden.net/upload/thumb/3/3e/039Jigglypuff.png/250px-039Jigglypuff.png',
FALSE
),
(
'Clevergirl',
'Raptor',
'5 years',
'Jurassic Park',
'Clever, cunning, lethal, protective, works best in a team',
'Cat-like reflexes, can jump and run extremely fast',
'Meat',
'Female',
'Queens',
'https://boingboing.net/filesroot/141_velociraptor.jpg',
FALSE
),
(
'Siggy, Molly, Scout, April, Eliza, Violet, Walter',
'7 Terminator Kittens',
'8 weeks',
'Backyard in Staten Island',
'Affectionate, playful, energetic, loyal, protective',
'Can shoot laser beams from their eyes',
'Chicken',
'6 Female, 1 Male',
'Staten Island',
'https://i.imgur.com/MC5npGi.jpg',
FALSE
),
(
'Hedwig',
'Snowy Owl',
'4 months',
'England',
'Intelligent, loyal, resourceful, affectionate, prous, dignified',
'Sends and delivers mail',
'Mice, rats, moles, squirrels, rabbits',
'Female',
'Manhattan',
'https://images.pottermore.com/bxd3o8b291gf/1YWQZuRbdOUQyYwgGkOoyy/76118bef757f01f32ae2ce838a74a69f/Hedwig_WB_F3_HedwigStill_Promo_100615_Port.jpg?w=1200',
false
),
(
'Coconut',
'Sloth',
'11 years',
'South America',
'Slow, lazy, affectionate, loving, loyal',
'None',
'Cecropia trees',
'Female',
'Bronx',
'https://gifts.worldwildlife.org/gift-center/Images/large-species-photo/large-Three-toed-Sloth-photo.jpg',
false
),
(
'Cheshire Cat',
'Magical Cat',
'45 years',
'Wonderland',
'Comical, Silly, Mysterious, Insane, Sneaky, Cunning, Mischievous, Unpredictable',
'Invisibility',
'Tuna',
'Genderless',
'Queens',
'https://upload.wikimedia.org/wikipedia/en/8/8e/DisneyCheshireCat.jpg',
false
),
(
'Fawkes',
'Phoenix',
'60 years',
'Unknown',
'Highly intelligent, loyal, protective, helpful',
'Healing tears, can lift great weight with tail when in flight, resurrection',
'Dragons',
'Male',
'Brooklyn',
'http://i.imgur.com/dZndGL7.png',
false
),
(
'Nala',
'Liger',
'2 years',
'Africa',
'Playful, territorial, affectionate, protective, brave, fierce',
'None',
'Meat',
'Female',
'Queens',
'http://animalsadda.com/wp-content/uploads/2016/07/liger-3.jpg',
false
),
(
'Donkey',
'Talking Donkey',
'6 years',
'Far Far Away',
'Talkative, friendly, helpful, loyal',
'Can talk',
'Grass, hay and straw',
'Male',
'Bronx',
'https://i.ytimg.com/vi/ovm2zkuqJD8/maxresdefault.jpg',
false
),
(
'Gwaihir',
'Great Eagle',
'528 years',
'Middle-earth',
'Loyal, intelligent, protective, majestic, brave, agile, graceful, courteous, fair',
'Capable of speech, immortal',
'Rabbits, marmots, and ground squirrels',
'Male',
'Brooklyn',
'https://pre01.deviantart.net/69ca/th/pre/f/2013/314/1/6/the_hobbit_eagle_by_jd1680a-d6tq67f.jpg',
false
),
(
'Jar Jar',
'Tauntaun',
'15 years',
'Planet Hoth',
'Friendly, loyal, obedient',
'None',
'Lichen and small ice plants',
'Genderless',
'Manhattan',
'http://nerdist.com/wp-content/uploads/2016/10/luke-tauntaun-538x500.jpg',
false
),
(
'Ghost',
'Direwolf',
'1 year',
'Westeros',
'Loyal, protective, brave, obedient, affectionate, intelligent',
'None',
'Meat',
'Male',
'Staten Island',
'http://cimg.tvgcdn.net/i/2016/05/09/078f20ce-b91a-4e58-b94b-7a8e4385c56d/gameofthrones-news.jpg',
false
),

(
    'Shippo',
    'Fox demon',
    '14 years',
    'Demon',
    'He is pretty jealous of her owner and loves young girls.',
    'He can transform himself in a large pink flying balloon or a mushroom. But his speciality is trickery, in fact he can create illusory duplicates of himself.',
    'Crayons and candies',
    'Male',
    'Bronx',
    'http://img00.deviantart.net/3e0f/i/2011/338/a/9/shippo_by_shadythecat-d4i6ek4.png',
    false
),
(
    'Kirara',
    'Cat demon',
    '16 years',
    'Demon',
    'Loyal and extremely clever, patiente and brave.',
    'When provoked or ready for battle she transforms into a very large, lion sized cat that can fly',
    'Fish',
    'Female',
    'Brooklyn',
    'https://img00.deviantart.net/6bfd/i/2009/290/c/c/baby_kirara_by_whittykitty.jpg',
    false
),
(
    'Luna',
    'Cat-like creature',
    '40 years',
    'Moon Kingdom',
    'Melodramatic manner when waking up in the morning, always giving unsolicited advices. She is extremely clever and she never hesitates to defend her owner when in danger.',
    'She can talk and turn into a young human girl, called Sailor Luna.',
    'Fish',
    'Female',
    'Manhattan',
    'https://s-media-cache-ak0.pinimg.com/originals/de/4f/08/de4f08fb3c47b4f6aff58f62c174392d.jpg',
    false
),
(
    'Genma Saotome',
    'Panda',
    '45 years',
    'Japan',
    'When he transforms into a middle-age man become really grumpy and stubborn.',
    'He is a martial art expert and he can write in Japanese.',
    'Ramen',
    'Male',
    'Queens',
    'http://www.kurogami.com/img/productos/figuras/ranma/figura-ranma-1-2-genma-saotome-figuarts-zero-01.jpg',
    false
),
(
    'Leonidas',
    'Catlion',
    '6 years',
    'Africa',
    'He likes to run in the backyards to catch his pray. In his spare time he prefers to sleep as long as possible and punch glass full of water on the floor.',
    'Little as a cat, but strong as a lion. He is very proud of his beautiful blond mane.',
    'Treats and fish',
    'Male',
    'Staten Island',
    'https://i.redd.it/5yqk0v3v6n2y.jpg',
    false
),
(
    'Francis',
    'Dog',
    '4 years',
    'Argentina',
    'He is a very religious dog. He usually like to wear white clothes.',
    'He is a good listener and always gives great advices. He is the pet you would ask for comforting when you are feeling down.',
    'Empanadas',
    'Male',
    'Bronx',
    'https://images.halloweencostumes.com/products/15022/1-1/holy-hound-pet-costume.jpg',
    false
),
(
    'Captain Datch',
    'Dog',
    '8 years',
    'Datchsund',
    'He is a playful, devoted, brave and stubborn dog. He really loves the sea and could stay hours staring at the horizon with his monocle.',
    'He can ride your boat on vacation since he has served in the navy as Captain.',
    'Hot dog',
    'Male',
    'Brooklyn',
    'https://i.pinimg.com/736x/cb/85/d6/cb85d60ec057d40584b9083b4b14ac1a--amazing-halloween-costumes-pet-costumes.jpg',
    false
),
(
    'Blink',
    'Dog',
    '4 years',
    'Chihuahua',
    'She likes punk music, loves to paint her hair and do stage diving during concerts.',
    'She can play the guitar and she is also a pretty good street artist.',
    'Junk food',
    'Female',
    'Manhattan',
    'https://i.pinimg.com/564x/8d/cb/43/8dcb433f57e6d1f1c02ac40c1ea3e5ea.jpg',
    false
),
(
    'Bob',
    'Dog',
    '8 years',
    'Basset Hound',
    'He loves Reggae music and big sunglasses. He used to smoke but he quit because he is getting old. ',
    'He is a terrific drum player and hairdresser, specialized in dreadlocks.',
    'Fried fish',
    'Male',
    'Queens',
    'https://i.pinimg.com/564x/bb/37/c8/bb37c861e01fea9490ccdeb69918eda6.jpg',
    false
),

('Boris', 'Dementor', '350 years', 'Harry Potter', 'Miserable', 'Sucks souls', 'Happiness', 'Genderless', 'Queens', 'https://www.hypable.com/wp-content/uploads/2015/05/Dementor-wasp-2.jpg', false),
  ('Sandy', 'Sandworm', '167 years', 'Arrakis', 'Chill', 'Quickly Burrows', 'Microorganisms, people', 'Genderless', 'Bronx', 'https://w-dog.net/wallpapers/16/2/477317265039412/art-sandworm-dune-chronicles-desert-sand-dune-the-worm-people-attack-transportation-plane-ships.jpg', false),
  ('Bigsly', 'Corim', '8 years', 'Wheel of Time', 'Energetic', 'Fast runner', 'Plants and Berries and stuff', 'Male', 'Manhattan', 'https://vignette.wikia.nocookie.net/wot/images/f/ff/Corlm.jpg/revision/latest?cb=20100416213801', false),
  ('Chris', 'Baby Chocobo', '1 year', 'Square Enix', 'Hungry', 'Runs Fast', 'Bugs', 'Male', 'Brooklyn', 'https://vignette.wikia.nocookie.net/finalfantasy/images/b/b1/PAD_Fat_Chocobo_artwork.png/revision/latest/zoom-crop/width/480/height/480?cb=20150415185850', false),
  ('Ammy', 'Amaterasu', '48 years', 'Asia', 'Playful', 'Shoots fire, ice and lightning', 'Veggies', 'Female', 'Staten Island', 'https://www.fightersgeneration.com/np5/more/amaterasu-mvc3.jpg', false),
  ('Norbert', 'Turtle', '208 years', 'Jones Beach', 'Pensive', 'Swims', 'Veggies, Insects, and Worms', 'Female', 'Staten Island', 'https://media.treehugger.com/assets/images/2013/10/desert_tortoise.jpg.662x0_q70_crop-scale.jpg', false),
  ('Puppy Litter', 'Rottweiler', '1 year', 'Sylvia’s backyard', 'Troublesome', 'Making Trouble', 'ANYTHING', 'Both', 'Brooklyn', 'http://www.revolution-kennel.com/wp-content/uploads/2014/02/S-Litter.jpg', false),
  ('Trunks', 'Parrot', '4 years', 'Brazilian Jungle', 'Vulgar', 'Flies', 'Fruit', 'Female', 'Manhattan', 'https://ak1.picdn.net/shutterstock/videos/1785971/thumb/1.jpg?i10c=img.resize(height:160)', false),
  ('Soren', 'Cat', '5 years', 'One of Liana’s Strays', 'Evil', 'Plots World Domination', 'The dog’s food…Nothing else', 'Male', 'Bronx', 'http://i.imgur.com/YPSjOCA.jpgv', false),
  ('Missy', 'Cat', '2 years', 'Another of Liana’s Strays', 'Happy Mad Yarn Skills Bruh', 'Loves EVERYONE.', 'Kibbles & Bits!', 'Female', 'Queens', 'http://s-ak.buzzfed.com/static/enhanced/terminal01/2010/10/13/14/enhanced-buzz-22200-1286995714-22.jpg', false),
  ('InkAY', 'Inkay - Pokemon', '2 years', 'Pokemon', 'Enigmatic', 'PSYCHIC', 'PokeBerries', 'No way to tell', 'Queens', 'https://img00.deviantart.net/b4d0/i/2015/111/4/6/inkay_by_reallydarkandwindie-d6d0t1h.png', false),
  ('BeetleBot', 'Medabot', '5 years', 'Medabots', 'Saucy', 'Shoots bullets and missiles. Seriously', 'Motor Oil Probably', 'Genderless', 'Bronx', 'https://i.pinimg.com/736x/6d/0f/a2/6d0fa225fcb0c5966a383d06a0987ccb--robot-art-anime-pictures.jpg', false),
  ('Alduin', 'Legendary Dragon', '780 years', 'Tamriel', 'PURE ACTUAL EVIL', 'BREATHES FIRE, ICE, LIGHTNING ANDDDD THE FORCE', 'Good countrymen', 'Male', 'Manhattan', 'https://vignette2.wikia.nocookie.net/tesfanon/images/5/57/AlDuin-elder-scrolls-v-skyrim-33221223-1131-707.jpg/revision/latest?cb=20131028174350', false),
  ('Baby Ri & Ra', 'Baby Rathian & Rathalos', '2 years', 'Monster Hunter', 'Playful', 'Flies, Breathes Fire, and Poisons People', 'Meat', 'Female & Male', 'Brooklyn', 'https://s3.amazonaws.com/colorslive/png/1096083-Y1vHk1cfcdrl4ohp.png', false),
  ('Sima', 'Nargacuga', '11 years', 'Monster Hunter', 'Predatory', 'Flies and shoots sharp Feathers', 'Meat/People', 'Female', 'Staten Island', 'https://vignette2.wikia.nocookie.net/monsterhunter/images/d/d4/2ndGen-Nargacuga_Render_003.png/revision/latest?cb=20150303085737', false),
  ('Zed', 'Aardvark', '7 years', 'Madagascar', 'Ambitious', 'Shuffles along with purpose', 'Insects', 'Female', 'Staten Island', 'http://www.nationalgeographic.com/content/dam/animals/thumbs/rights-exempt/mammals/a/aardvark_thumb.ngsversion.1474903830105.adapt.1900.1.JPG', false),
  ('Mini Moo', 'Small Cow', '5 years', 'Upstate NY', 'Pensive', 'Feeding all these stomaches is hard work too', 'Grass', 'Male', 'Brooklyn', 'http://nebula.wsimg.com/9acaf497794486e48eff6b6647895dde?AccessKeyId=AA3C537AACF397A1F823&disposition=0&alloworigin=1', false),
  ('Moody', 'Vulture', '9 years', 'Gobi Dessert', 'Funny', 'Flies', 'Dead Things', 'Male', 'Manhattan', 'http://www.birdlife.org/sites/default/files/gyps_fulvus_-_01_1.jpg', false),
  ('BaRoo', 'Baby Kangaroo', '1 year', 'Australia', 'Hoppy', 'Hops at the speed of light', 'Milk', 'Female', 'Bronx', 'https://grist.files.wordpress.com/2012/11/baby_kangaroo.jpeg?w=970', false),
  ('Yaali', 'Baby Tiger', '2 years', 'Himalayas', 'Curious', 'Tree Climber, frost breath', 'Meat', 'Female', 'Queens', 'http://www.cutestpaw.com/wp-content/uploads/2013/03/Baby-white-tiger.jpg', false),

  (
    'Pingu',
    'Penguin',
    '5 years',
    'South Pole',
    'Playful, sometimes naughty, he is an extremely curious little penguin.',
    'He can speak Penguinese',
    'Frozen fish',
    'Male',
    'Staten Island',
    'http://i.imgur.com/oAYK6.jpg',
    false
),
(
    'Dumbo',
    'Octopus',
    '3 years',
    'Umbrella Octopus',
    'He is a very shy octopus, he likes to stay in the dark in his little aquarius and swim in very cold water.',
    'He can only swim slowly, flapping his ear-like fins and use his arm to steer',
    'Little fishes',
    'Male',
    'Brooklyn',
    'https://static.boredpanda.com/blog/wp-content/uuuploads/strange-animals-you-didnt-know/strange-animals-you-didnt-know-7-1.jpg',
    false
),
(
    'Glow',
    'Turtle',
    '5 years',
    'Tropics',
    'She is usually a solitary turtle, but on Friday night she loves going to the club and wear her fluorescent shell.',
    'Thanks to her glowing shell she is the party queen and she is also loved by kids because she keep the light up at night. She is the perfect pet for your children!',
    'She is vegetarian and loves lettuce',
    'Female',
    'Bronx',
    'http://awesomeocean.com/wp-content/uploads/2016/06/first-image-of-fluorescentHawksbillTurtle.jpg',
    false
),
(
    'Cindy',
    'Fish',
    '2 years',
    'Galapagos',
    'She is passionate of make-up and she owns a stunning collection of lipsticks.',
    'She is not a good swimmer, so she prefers to lay down on the bottom of the aquarius chilling out.',
    'Shrimps',
    'Female',
    'Brooklyn',
    'https://static.boredpanda.com/blog/wp-content/uuuploads/strange-animals-you-didnt-know-2/strange-animals-you-didnt-know-2-2.jpg',
    false
),
(
    'Blue',
    'Dragon',
    '4 years',
    'Australia',
    'He is passionate about hunting and loves to swim in warm water. It would be better not to provoke him because he has a very short temper.',
    'He can roll into a little ball and hide himself in the aquarium.',
    'Little fish',
    'Non-gendered',
    'Queens',
    'https://static.boredpanda.com/blog/wp-content/uuuploads/strange-animals-you-didnt-know-2/strange-animals-you-didnt-know-2-16-2.jpg',
    false
),
(
    'Luhu',
    'Cat',
    '4 years',
    'China',
    'She is usually extremely sad and looking for infinite cuddles. She also loves listening to lullabies before going to bed.',
    'You cannot say no to those sad eyes, so she basically can get whatever she wants without even meaowing.',
    'Tuna',
    'Female',
    'Manhattan',
    'https://static.boredpanda.com/blog/wp-content/uploads/2017/09/saddest-cat-luhu-maggie-liu-lanlan731-38-59c0bfed09657__700.jpg',
    false
),
(
    'Babe',
    'Pig',
    '2 years',
    'United Kingdom',
    'He is a very spoiled puppy and loves to be cuddled. If you do not pet him enough he will tease you to steal your attentions.',
    'He can jump in mud puddles all day long and never get tired.',
    'Ice cream',
    'Male',
    'Queens',
    'http://greatinspire.com/wp-content/uploads/2013/07/35-Cute-Miniature-Pig-Pictures-19.jpg',
    false
),
(
    'Bunnie',
    'Bunny',
    '5 years',
    'France',
    'She likes math and physics and she spend most of her day studying.',
    'She can help your children with homeworks and assignements, since she is also passionate about teaching. If you are looking for the right pet for your kids, she is the one!',
    'Carrots',
    'Female',
    'Staten Island',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdx37hmV418N_S8woUg6Hv1dXyVElD17UNJ8UCMh2qKRAgeWL6',
    false
),
(
    'Granpa',
    'Squirrel',
    '18 years',
    'USA',
    'Granpa is a little old squirrel looking for a lovely family where he can spend the rest of his time. He is passionate about storytelling and has a lot of amazing stories to entertain you in those rainy winter days',
    'He cannot jump and run anymore, but with his little walker can stll do long walks while looking for hazelnuts on his way.',
    'Hazelnuts',
    'Male',
    'Bronx',
    'https://www.askideas.com/media/15/Handicapped-Squirrel-Funny-Picture.jpg',
    false
),
(
    'Cookie',
    'Pony',
    '8 years',
    'Germany',
    'Cookie is a sweet pony who pretends to be a dog. She loves to be cuddled and steal you seat on the couch to take a little nap.',
    'Since her granma was a unicorn, she inherited the ability to move objects with telekinesis or let them disappear. Usually she exercise her ability with food. With her favorite brand of cereal, to be precise.',
    'Cereals',
    'Female',
    'Brooklyn',
    'https://i.pinimg.com/736x/bf/9c/22/bf9c22a430ec0b8e40ccec76ede1c1b4--hammerhead-shark-whale-sharks.jpg',
    false
),
(
    'Kuzco',
    'Llama',
    '8 years',
    'South America',
    'Kuzco is passionate about fashion and hair styiling. He loves to see fashion shows in tv and spends a lot of time every morning to do his hair.',
    'He will not only be your devoted llama pet, but also your faithful hairstylist.',
    'Tacos',
    'Male',
    'Queens',
    'http://thefw.com/files/2012/11/tumblr_ls6ujhB6wV1qfq9oxo1_5001.jpg',
    false
);
